### ISSUE TITLE
Error in ScoreTest_SPA

### ISSUE THREAD

**Issue by dineshpeace** [leeshawn/SPAtest#1]
Following error will performing ScoreTest_SPA

"Error in `[[<-.data.frame`(`*tmp*`, i, value = c(66L, 114L, 154L, 194L, :
replacement has 18639 rows, data has 6213"

My hla.dosage has 6213 samples

**My covariate file**
sample.id cov1 cov2  cov3
000889_0300056991  14  M  6.6
000891_0300042621  20  M  7.2

**My Phenotype file**
sample.id  Tpheno
000889_0300056991 1
000891_0300042621 1
000911_0300032341 1
000919_0300018171 2

**CODE**
phewas <- lapply(2:ncol(phenos), function(i) {
  
  print(i)
  
  # input for spatest
  tmp.cov    <- inner_join(na.omit(phenos[, c(1, i)]), covs, by='sample.id')
  tmp.pheno  <- tmp.cov[, 2]
  tmp.cov    <- tmp.cov[, -2]
  tmp.dosage <- left_join(tmp.cov[, 1:2], hla.dosage)
  tmp.dosage <- tmp.dosage[, -c(1:2)]
  tmp.cov    <- select(tmp.cov, -sample.id) 
  
  # run test
  tmp <- ScoreTest_SPA(as.matrix(t(tmp.dosage)), tmp.pheno, tmp.cov, beta.out=T, beta.Cutoff=0.05)
  tmp <- do.call(cbind, tmp)
  data.frame(locus=colnames(tmp.dosage), tmp)
  
})

**Comment by rounakdey** [comment]
ScoreTest_SPA does not handle factors as inputs. Changing cov2 into numeric dummy variables solved this issue. Also, the phenotype needs to be in 0/1 format, not 1/2 format. 0 represents controls, 1 represents cases.
